include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    variables:
        APP_ID: org.gnome.PasswordSafeDevel
        MANIFEST_PATH: "flatpak/org.gnome.PasswordSafe.json"
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "passwordsafe"
        MESON_ARGS: "-Dprofile=development"
        BUNDLE: "org.gnome.PasswordSafeDevel.flatpak"
    extends: .flatpak
