include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - check
  - build
  - deploy

variables:
    BUNDLE: "org.gnome.World.Secrets.Devel.flatpak"
    MANIFEST_PATH: "flatpak/org.gnome.World.Secrets.Devel.json"
    FLATPAK_MODULE: "secrets"

.flatpak_cache_template: &flatpak_cache
    cache:
        key: "flatpak"
        paths:
          - .flatpak-builder/cache/
          - _build/target/

flatpak:
    extends: .flatpak
    stage: build
    variables:
        APP_ID: org.gnome.World.Secrets.Devel
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

codespell:
  stage: check
  script:
    - dnf install -y codespell
    - codespell -S "*.png,*.po,.git,*.jpg,eff_large_wordlist.txt,.mypy_cache,_build" -f

flake8:
  stage: check
  script:
    - dnf install -y python3-flake8 pip
    - pip install pyotp
    - flake8 --max-line-length=88 --ignore=E402,W503 --show-source gsecrets

mypy:
  stage: check
  script:
    - dnf install -y pip
    - pip install mypy pyotp
    - mypy --ignore-missing-imports --disallow-incomplete-defs gsecrets

pylint:
  stage: check
  script:
    - dnf install -y 'dnf-command(copr)'
    - dnf install -y libadwaita-devel gtk4-devel libpwquality-devel pip pylint python3-pwquality python3-gobject-devel python3-pykeepass
    - pip install pyotp
    - mv gsecrets/const.py.in gsecrets/const.py  # We need a dummy file
    - pylint --rcfile=.pylintrc gsecrets
