include: 'https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml'

stages:
  - check
  - build
  - deploy

variables:
    BUNDLE: "org.gnome.PasswordSafe.Devel.flatpak"
    MANIFEST_PATH: "flatpak/org.gnome.PasswordSafe.Devel.json"
    FLATPAK_MODULE: "passwordsafe"

.flatpak_cache_template: &flatpak_cache
    cache:
        key: "flatpak"
        paths:
          - .flatpak-builder/cache/
          - _build/target/

flatpak:
    extends: .flatpak
    stage: build
    variables:
        APP_ID: org.gnome.PasswordSafe.Devel
        RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
        MESON_ARGS: "-Dprofile=development"

codespell:
  stage: check
  script:
    - dnf install -y codespell
    - codespell -S "*.png,*.po,.git,*.jpg,eff_large_wordlist.txt,.mypy_cache,_build" -f

flake8:
  stage: check
  script:
    - dnf install -y python3-flake8 python3-pyotp
    - flake8 --max-line-length=170 --ignore=E402,W503 --show-source passwordsafe

mypy:
  stage: check
  script:
    - dnf install -y pip python3-pyotp
    - pip install mypy
    - mypy --ignore-missing-imports --disallow-incomplete-defs passwordsafe
