stages:
  - flatpak

variables:
  BUNDLE: "password-store-git.flatpak"


flatpak:
    image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
    stage: flatpak
    variables:
        MANIFEST_PATH: "flatpak/run.terminal.KeepassGtk.json"
        RUNTIME_REPO: "https://sdk.gnome.org/gnome-nightly.flatpakrepo"
        FLATPAK_MODULE: "keepassgtk"
    script:
        - flatpak-builder --stop-at=${FLATPAK_MODULE} app ${MANIFEST_PATH}
        - flatpak build app meson --prefix=/app ${MESON_ARGS} _build
        - flatpak build app ninja -C _build install
        - flatpak-builder --finish-only --repo=repo app ${MANIFEST_PATH}
        - flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} run.terminal.KeepassGtk
    artifacts:
        paths:
            - ${BUNDLE}
            - _build/meson-logs/meson-log.txt
        expire_in: 30 days
    cache:
        paths:
             - .flatpak-builder/cache
